frontend:
  image: dowenliu/frontend
  tag: latest
  autoscaling:
    averageUtilization: 90

backend:
  image: dowenliu/backend
  tag: latest
  autoscaling:
    averageUtilization: 90

database:
  enabled: true
  uri: pg-service
  username: postgres
  password: postgres

