frontend:
  image: dowenliu/frontend
  tag: bb46910
  autoscaling:
    averageUtilization: 90
backend:
  image: dowenliu/backend
  tag: bb46910
  autoscaling:
    averageUtilization: 90
database:
  enabled: true
  uri: pg-service
  username: postgres
  password: postgres
